# Generated by Django 3.2.7 on 2021-09-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cost', models.IntegerField()),
                ('pdf', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tipe')),
            ],
        ),
    ]
