# Generated by Django 3.2.7 on 2021-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_dish_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
