# Generated by Django 3.2.7 on 2021-09-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_dish_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
