# Generated by Django 3.2.7 on 2021-09-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('service', '0004_auto_20210912_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_cust', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_profile', to='users.profile'),
        ),
    ]
