# Generated by Django 3.2.7 on 2021-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210913_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singular',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
