# Generated by Django 3.2.7 on 2021-09-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount_per_kilo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bill')),
                ('ingrediant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingrediant')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField()),
                ('ingrediant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingrediant')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.measurement')),
            ],
        ),
    ]
