# Generated by Django 3.2.7 on 2021-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='amount_per_kilo',
            field=models.FloatField(),
        ),
    ]
