# Generated by Django 3.2.7 on 2021-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_measurement_amount_per_kilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='cost',
            field=models.FloatField(),
        ),
    ]
